# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a69b2be664bacaf9f5ba5f78593b6bad390d643e1ac1ef065c96525080844691bd6d82edc0b87f1eed891a5d54cb3ed039bd4964f43795401fc3cf66ea0f17

test:
  secret_key_base: 03586ebc6d1e66e3d7641d0b9e53effa214c9b0fe41dec9cb76fc54b0c8bd956bd887bbcbb59293a7746c113d38beab805100e4faba192248870c1170223f827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
